### ISSUE TITLE
onBlur

### ISSUE THREAD

**Issue by DhyeyMoliya** [KamyarLajani/svelte-yup#1]
This is a great concept for form validation. 

Can there be an option of validation `onBlur`? So that user does not have to wait until submission.

**Comment by KamyarLajani** [comment]
Unfortunately this library design is not comfortable with this feature.
It needs some changes to the design. But it can be change in the future.

**Comment by Shekhar-Zealous** [comment]
@KamyarLajani Are you working on the below feature?

> Can there be an option of validation `onBlur`? So that user does not have to wait until submission.

A much required feature to use it for multi step forms.
