### ISSUE TITLE
A question about "Please fill out this field." message

### ISSUE THREAD

**Issue by madrus** [KamyarLajani/svelte-yup#6]
Hi Kamyar, what a great tool you have built! I especially bewonder the highest quality of your code in the sense of its structure. No code duplication and everything is logically arranged. Much to learn from.

Now, I have noticed a message popping up every time I try to submit a form with one of the required fields not filled.

![image](https://user-images.githubusercontent.com/7058116/209460318-6438765d-a650-401b-beec-0cc6ec29467c.png)

However, I cannot find this message anywhere in your code nor in  the [yup](https://github.com/jquense/yup) repo. Where does it come from? It is a handy message but I actually need it in another language and in another color. Could you give me a hint how this can be done? Much appreciated.

**Comment by KamyarLajani** [comment]
Hello.
Thank you.
The messages are came from Yup library.
And yes you can also change the message and change the message text to
another language.
See the Yup library documentation here:
https://www.npmjs.com/package/yup
For the color message you can change it in my Svelte-yup library. There is
a prop called color and pass it in the Form component.


<Form ... color="#b00020">


Thank you.

**Comment by madrus** [comment]
> See the Yup library documentation here: https://www.npmjs.com/package/yup

Thank you, Kamyar! I will. I have cloned the yup repo locally and could not fine the string in the whole code base. Strange...

> For the color message you can change it in my Svelte-yup library.

I actually was thinking not of the message under the field but the black background and white font of the pop-up notification message (see the picture I have added in my first comment).

**Comment by madrus** [comment]
It appears that this message does not come from your `svelte-yup` nor from `yup` at all. It comes from the browser default validation of the form unless one adds a `novalidate` attribute to it. Which I did by adding it to your `Form` tag in my code. No error tooltips any more! Only the configured error messages from my schema.
